// Generated by gencpp from file servingbot_msgs/SensorState.msg
// DO NOT EDIT!


#ifndef SERVINGBOT_MSGS_MESSAGE_SENSORSTATE_H
#define SERVINGBOT_MSGS_MESSAGE_SENSORSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace servingbot_msgs
{
template <class ContainerAllocator>
struct SensorState_
{
  typedef SensorState_<ContainerAllocator> Type;

  SensorState_()
    : header()
    , illumination(0.0)
    , led(0)
    , button(0)
    , torque(false)
    , left_encoder(0)
    , right_encoder(0)  {
    }
  SensorState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , illumination(0.0)
    , led(0)
    , button(0)
    , torque(false)
    , left_encoder(0)
    , right_encoder(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _illumination_type;
  _illumination_type illumination;

   typedef uint8_t _led_type;
  _led_type led;

   typedef uint8_t _button_type;
  _button_type button;

   typedef uint8_t _torque_type;
  _torque_type torque;

   typedef int32_t _left_encoder_type;
  _left_encoder_type left_encoder;

   typedef int32_t _right_encoder_type;
  _right_encoder_type right_encoder;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(BUTTON0)
  #undef BUTTON0
#endif
#if defined(_WIN32) && defined(BUTTON1)
  #undef BUTTON1
#endif
#if defined(_WIN32) && defined(ERROR_LEFT_MOTOR)
  #undef ERROR_LEFT_MOTOR
#endif
#if defined(_WIN32) && defined(ERROR_RIGHT_MOTOR)
  #undef ERROR_RIGHT_MOTOR
#endif
#if defined(_WIN32) && defined(TORQUE_ON)
  #undef TORQUE_ON
#endif
#if defined(_WIN32) && defined(TORQUE_OFF)
  #undef TORQUE_OFF
#endif

  enum {
    BUTTON0 = 1u,
    BUTTON1 = 2u,
    ERROR_LEFT_MOTOR = 1u,
    ERROR_RIGHT_MOTOR = 2u,
    TORQUE_ON = 1u,
    TORQUE_OFF = 2u,
  };


  typedef boost::shared_ptr< ::servingbot_msgs::SensorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::servingbot_msgs::SensorState_<ContainerAllocator> const> ConstPtr;

}; // struct SensorState_

typedef ::servingbot_msgs::SensorState_<std::allocator<void> > SensorState;

typedef boost::shared_ptr< ::servingbot_msgs::SensorState > SensorStatePtr;
typedef boost::shared_ptr< ::servingbot_msgs::SensorState const> SensorStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::servingbot_msgs::SensorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::servingbot_msgs::SensorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::servingbot_msgs::SensorState_<ContainerAllocator1> & lhs, const ::servingbot_msgs::SensorState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.illumination == rhs.illumination &&
    lhs.led == rhs.led &&
    lhs.button == rhs.button &&
    lhs.torque == rhs.torque &&
    lhs.left_encoder == rhs.left_encoder &&
    lhs.right_encoder == rhs.right_encoder;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::servingbot_msgs::SensorState_<ContainerAllocator1> & lhs, const ::servingbot_msgs::SensorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace servingbot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::servingbot_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::servingbot_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servingbot_msgs::SensorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::servingbot_msgs::SensorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servingbot_msgs::SensorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::servingbot_msgs::SensorState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::servingbot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "35fc4701cdd5877471c35f7246cdb2c7";
  }

  static const char* value(const ::servingbot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x35fc4701cdd58774ULL;
  static const uint64_t static_value2 = 0x71c35f7246cdb2c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::servingbot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "servingbot_msgs/SensorState";
  }

  static const char* value(const ::servingbot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::servingbot_msgs::SensorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "########################################\n"
"# CONSTANTS\n"
"########################################\n"
"# Button states (states are combined, when multiple buttons are pressed)\n"
"uint8 BUTTON0 = 1\n"
"uint8 BUTTON1 = 2\n"
"\n"
"# Motor errors\n"
"uint8 ERROR_LEFT_MOTOR  = 1\n"
"uint8 ERROR_RIGHT_MOTOR = 2\n"
"\n"
"# Motor torque\n"
"uint8 TORQUE_ON  = 1\n"
"uint8 TORQUE_OFF = 2\n"
"\n"
"########################################\n"
"# Messages\n"
"########################################\n"
"Header  header\n"
"float32 illumination\n"
"uint8   led\n"
"uint8  button\n"
"bool   torque\n"
"int32  left_encoder    # (-2,147,483,648 ~ 2,147,483,647)\n"
"int32  right_encoder   # (-2,147,483,648 ~ 2,147,483,647)\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::servingbot_msgs::SensorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::servingbot_msgs::SensorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.illumination);
      stream.next(m.led);
      stream.next(m.button);
      stream.next(m.torque);
      stream.next(m.left_encoder);
      stream.next(m.right_encoder);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::servingbot_msgs::SensorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::servingbot_msgs::SensorState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "illumination: ";
    Printer<float>::stream(s, indent + "  ", v.illumination);
    s << indent << "led: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.led);
    s << indent << "button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button);
    s << indent << "torque: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.torque);
    s << indent << "left_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_encoder);
    s << indent << "right_encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_encoder);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVINGBOT_MSGS_MESSAGE_SENSORSTATE_H
